INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NBA X NIKE LA CLIPPERS ICON SWINGMAN JERSEY', 1, 'Nike', 'blue', 'LA Clippers jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NBA X NIKE NEW ORLEANS PELICANS SWINGMAN JERSEY', 2, 'Nike', 'black', 'New Orleans Pelicans jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NIKE X NBA LOS ANGELES LAKERS SWINGMAN JERSEY', 3, 'Nike', 'yellow', 'LA Lakers jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NIKE X NBA PHILADELPHIA 76ERS  SWINGMAN JERSEY', 4, 'Nike', 'light blue', 'Philadelphia 76ers jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NBA X NIKE BROOKLYN NETS SWINGMAN JERSEY', 5, 'Nike', 'white', 'Brooklyn Nets jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NBA X NIKE GOLDEN STATE WARRIORS SWINGMAN JERSEY', 6, 'Nike', 'dark blue', 'Golden State Warriors jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NBA X  NIKE UTAH JAZZ SWINGMAN JERSEY', 7, 'Nike', 'dark green', 'Utah Jazz jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NBA X NIKE HOUSTON ROCKETS SWINGMAN JERSEY', 8, 'Nike', 'red', 'Houston Rockets jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('MITCHELL & NESS CHICAGO BULLS SWINGMAN JERSEY', 9, 'MITCHELL & NESS', 'garnet' ,'Chicago Bulls jersey');
INSERT INTO jersey(name, club_id, brand, color, description) VALUES ('NBA X NIKE SACRAMENTO KINGS JERSEY', 10, 'Nike', 'light red', 'Sacramento Kings jersey');

INSERT INTO basket_club(club_name, club_description) VALUES ('Los Angeles Clippers', 'For most of their history the Los Angeles Clippers have been synonymous with losing. In all of the major sports in the United States, the Clippers along with maybe four other teams were the embodiment of failure. The Clippers are on pace to make the playoffs as one of the top four seeds, and they are one of the most entertaining teams in the NBA to watch along with the Miami Heat. The sky is the limit for this team.');
INSERT INTO basket_club(club_name, club_description) VALUES ('New Orleans Pelicans', 'The New Orleans Pelicans have only been a team in the NBA for 23 years, but they have been on the move during those years. In 1988, the NBA expanded adding the Pelicans and the Miami Heat. They were not the New Orleans Pelicans though. They came into the league as the Charlotte Hornets. Most new teams struggle in their first few years in the NBA, and the Pelicans were no different. The difference with the Pelicans was that despite the struggles the first few years, they led the NBA in fan attendance in 8 of their first 10 seasons.');
INSERT INTO basket_club(club_name, club_description) VALUES ('Los Angeles Lakers', 'The Los Angeles Lakers are one of the oldest and most revered teams in the NBA. Other teams might talk about how many times they have made the playoffs or won their division, but the Lakers talk about their 16 NBA championships. There will always be debate about who the best players in NBA history have been, but depending who you ask there could easily be four Lakers in the top ten best NBA players of all time. They joined the NBA in 1947 as the Minneapolis Lakers. Minneapolis is located in the state of Minnesota which has the nickname of “land of a thousand lakes.” This is why the team chose to be called the Lakers.');
INSERT INTO basket_club(club_name, club_description) VALUES ('Philadelphia 76ers', 'The Philadelphia 76ers became a professional basketball team in 1946 which was before the NBA was in existence. When two leagues merged to form the NBA, the Syracuse Nationals were one of the teams to beat early on. The Nationals played in the first even NBA Finals against the Minneapolis Lakers. The Lakers would go on to win the title. The Nationals would win their first championship a few years later when they defeated the Fort Wayne Pistons in a thrilling game seven win.');
INSERT INTO basket_club(club_name, club_description) VALUES ('Brooklyn Nets', 'The Brooklyn Nets were one of the four teams to join the NBA in the ABA-NBA merger in 1976. The Nets were successful in the ABA before the merger. They were able to win two championships in their ABA days. The team did not begin as the New Jersey Nets though. They began as the New York Americans, but before they ever played a game they were relocated across the river to New Jersey. The Nets ended up moving back into New York and played most of their time in the ABA as the New York Nets. The Nets won their two ABA championships behind the play of Julius Erving also known as “Dr. J.” He won the league MVP, and he is still considered today one of the best players and dunkers in the history of basketball.');
INSERT INTO basket_club(club_name, club_description) VALUES ('Golden State Warriors', 'The Golden State Warriors have the claim to fame that can never be taken away from them. The Warriors won the first ever championship. The Warriors are such an old team that their first title came before the NBA. The Warriors were located in Philadelphia when they won the first ever Basketball Association of America (BAA) championship. After two more seasons as the BAA, the BAA and the National Basketball League (NBL) merged to form the NBA.');
INSERT INTO basket_club(club_name, club_description) VALUES ('Utah Jazz', 'The Utah Jazz history can be broken up into three sections: before Karl Malone and John Stockton, during Malone and Stockton, and after Malone and Stockton. That is how much these two players did for the franchise. The Jazz struggled early on in the NBA. They started out as the New Orleans Jazz in 1974. Early on they traded for NBA star and former local college star “Pistol” Pete Maravich. He led the NCAA in scoring average over a career, and he led the NBA in scoring one season.');
INSERT INTO basket_club(club_name, club_description) VALUES ('Houston Rockets','As with most teams in the NBA, the Houston Rockets did not begin as the rockets. The franchise has always gone by the moniker Rockets, but they entered the league in 1967 as the San Diego Rockets. The Rockets moved to Houston in 1971 where they have been ever since. During the dark few seasons in the league, the Rockets were getting some of the first picks in the NBA draft. It was with their first pick in 1969 that they selected Elvin Hayes. Hayes is very important to the Rockets history because in his rookie season, he led the Rockets to their first ever trip to the playoffs. After a few very good seasons for the Rockets, Hayes was traded away.');
INSERT INTO basket_club(club_name, club_description) VALUES ('Chicago Bulls', 'The Chicago Bulls are historically the third pro basketball team to find a home in the Windy City. Created in 1966 as an expansion franchise, they currently play in the Central Division of the Eastern Conference.The history of the Chicago Bulls is, more than any other team in history, linked to one single player, five-time MVP Michael Jordan. While in Chicago, Jordan led the Bulls to six championships, making them the third most-titled franchise in NBA history, just behind the legendary Boston Celtics and Los Angeles Lakers. After being the team of the 1990s and helping NBA become the global force it is today, the Chicago Bulls are now witnessing the rise of a new generation.');
INSERT INTO basket_club(club_name, club_description) VALUES ('Sacramento Kings', 'Having the name the Kings implies that this team would be one of the top teams in the NBA. They should be the rulers of the league. That is not the case though. It has hardly ever been the case for the Sacramento Kings. In 1945 the franchise came into existence as the Rochester Royals. This was before the merger of the National Basketball League (NBL) and the Basketball Association of America. The Kings played in the NBL for a few seasons before they switched to the BAA. A year later the two leagues merged to form the NBA in 1949. It was in the early years that the Rochester Royals played like royalty. They were the elite of the league when they joined the NBL. In their first season, they won the NBL championship. In their years in the NBL, the Royals finished as one of the best teams in the league every year. The same was true when they moved to the BAA and then to the NBA in the merger.');

INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (1, 'Thomson Jake Logan', 'Mr.', 'M', '78 Santa Monica Bd.', 'logan.thomson@laclippers.com', '202-555-0139');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (2, 'Mathias Edison', 'Dr.', 'M', '134 Downtown Avenue', 'mathias.edison@nopelicans.com', '202-555-2451');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (3, 'Sandra Kirk', 'Miss', 'F', '4995 George Avenue', 'sandra.kirk@lalakers.com', '202-445-3041');
INSERT INTO club_personnel(club_id, name, gender, address, email, phone_number) VALUES (4, 'Kane Woodcock', 'M', '4492  Freed Drive', 'kane.woodcock@philadelphia-ers.com','202-419-4901');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (5, 'Alisha Hastings', 'Miss', 'F',' 1085  Heavner Court', 'alisha.hastings.brooklynnets.com','202-333-4444');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (6, 'Eduard Halliday', 'Lord', 'M', '5027  Prudence Street', 'eduard.halliday@goldenstate.com', '202-214-215');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (7, 'Giselle Whyte', 'Mrs', 'F', '4136  Moore Avenue',  'giselle.whyte@utahjazz.com', '202-919-5731');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (8, 'Ema Reyna', 'Miss', 'F', '5005  Wetzel Lane', 'ema.reyna@houston.rockets.com', '202-884-1999');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (9, 'Konrad Blankenship', 'Dr.', 'M', '2025  Valley Lane', 'konrad.blankenship@chicagobulls.com', '241-445-1456');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (10, 'Stuart Wolf', 'Mr.', 'M', '1022  Oak Way', 'stuart.wolf@sacramento-kings.com', '245-456-0994');
INSERT INTO club_personnel(club_id, name, title, gender, address, email, phone_number) VALUES (10, 'Scott McTominay', 'Mr.', 'M', '200 Palm Street', 'scott.mctominay@sacramento-kings.com', '245-555-3415');

INSERT INTO locations(name, address, capacity) VALUES ('Staples Center', '1111 South Figueroa Street', 19000);
INSERT INTO locations(name, address, capacity) VALUES ('Ford Center', '100 West Reno Avenue', 19164);
INSERT INTO locations(name, address, capacity) VALUES ('Wells Fargo Center', '3601 South Broad Street', 20478);
INSERT INTO locations(name, address, capacity) VALUES ('Barclays Center', '620 Atlantic Avenue', 17732);
INSERT INTO locations(name, address, capacity) VALUES ('Chase Center', '1 Warriors Way', 18064);
INSERT INTO locations(name, address, capacity) VALUES ('Vivint Arena', '301 W. South Temple', 18306);
INSERT INTO locations(name, address, capacity) VALUES ('Toyota Center', '1510 Polk Street', 18055);
INSERT INTO locations(name, address, capacity) VALUES ('United Center', '1901 West Madison Street', 20917);
INSERT INTO locations(name, address, capacity) VALUES ('Golden 1 Center', '500 David J. Stern Walk', 17583);
INSERT INTO locations(name, address, capacity) VALUES ('Phoenix Suns Arena', '201 East Jefferson Street', 18055);

INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (1,1,2, '2021/03/03', 'Clippers winning by 20 points', '99-79');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (3,3,4, '2021/03/25', 'Lakers had 0 eliminations', '100-98');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (5,5,6, '2021/03/24', 'Warriors had 10 3 points', '118-100');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (7,7,8, '2021/03/29', 'Rockets scored an equaliser in the last minute','110-110');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (9,9,10, '2021/04/01', 'Bulls easily winning the game', '107-90');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (6,6,2, '2021/04/09', 'Warriors winning easily, Stephen Curry scored 5 x 3 points', '98-68');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (10,10,1, '2021/04/09', 'Equal game, draw was the correct result', '98-98');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (8,8,4, '2021/04/14', 'Rockets doing a completly show', '120-90');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (4,4,7, '2021/04/15', 'There was a fight, 2 eliminations', '90-103');
INSERT INTO games(club_id, location_id, opponent_club_id, game_date, game_description, game_result) VALUES (2,2,10, '2021/04/15', 'Kings winning with a 3 pointer in the last 2 seconds', '105-108');
     

    

